-- Inserção de 100 carros
INSERT INTO carros (serial, nome, fabricante)
VALUES
    ('CAR-001', 'Honda Civic', 'Honda'),
    ('CAR-002', 'Toyota Corolla', 'Toyota'),
    ('CAR-003', 'Ford Focus', 'Ford'),
    ('CAR-004', 'Chevrolet Malibu', 'Chevrolet'),
    ('CAR-005', 'BMW 3 Series', 'BMW'),
    ('CAR-006', 'Audi A4', 'Audi'),
    ('CAR-007', 'Mercedes-Benz C-Class', 'Mercedes-Benz'),
    ('CAR-008', 'Volkswagen Passat', 'Volkswagen'),
    ('CAR-009', 'Hyundai Sonata', 'Hyundai'),
    ('CAR-010', 'Kia Optima', 'Kia'),
    ('CAR-011', 'Nissan Altima', 'Nissan'),
    ('CAR-012', 'Subaru Legacy', 'Subaru'),
    ('CAR-013', 'Mazda6', 'Mazda'),
    ('CAR-014', 'Toyota Camry', 'Toyota'),
    ('CAR-015', 'Chevrolet Cruze', 'Chevrolet'),
    ('CAR-016', 'Ford Fusion', 'Ford'),
    ('CAR-017', 'Honda Accord', 'Honda'),
    ('CAR-018', 'BMW 5 Series', 'BMW'),
    ('CAR-019', 'Audi A6', 'Audi'),
    ('CAR-020', 'Mercedes-Benz E-Class', 'Mercedes-Benz'),
    ('CAR-021', 'Volkswagen Jetta', 'Volkswagen'),
    ('CAR-022', 'Hyundai Elantra', 'Hyundai'),
    ('CAR-023', 'Kia Forte', 'Kia'),
    ('CAR-024', 'Nissan Sentra', 'Nissan'),
    ('CAR-025', 'Subaru Impreza', 'Subaru'),
    ('CAR-026', 'Mazda3', 'Mazda'),
    ('CAR-027', 'Chevrolet Sonic', 'Chevrolet'),
    ('CAR-028', 'Ford Escape', 'Ford'),
    ('CAR-029', 'Toyota RAV4', 'Toyota'),
    ('CAR-030', 'Honda CR-V', 'Honda'),
    ('CAR-031', 'BMW X3', 'BMW'),
    ('CAR-032', 'Audi Q5', 'Audi'),
    ('CAR-033', 'Mercedes-Benz GLC', 'Mercedes-Benz'),
    ('CAR-034', 'Volkswagen Tiguan', 'Volkswagen'),
    ('CAR-035', 'Hyundai Tucson', 'Hyundai'),
    ('CAR-036', 'Kia Sportage', 'Kia'),
    ('CAR-037', 'Nissan Rogue', 'Nissan'),
    ('CAR-038', 'Subaru Forester', 'Subaru'),
    ('CAR-039', 'Mazda CX-5', 'Mazda'),
    ('CAR-040', 'Chevrolet Equinox', 'Chevrolet'),
    ('CAR-041', 'Ford Explorer', 'Ford'),
    ('CAR-042', 'Toyota Highlander', 'Toyota'),
    ('CAR-043', 'Honda Pilot', 'Honda'),
    ('CAR-044', 'BMW X5', 'BMW'),
    ('CAR-045', 'Audi Q7', 'Audi'),
    ('CAR-046', 'Mercedes-Benz GLE', 'Mercedes-Benz'),
    ('CAR-047', 'Volkswagen Atlas', 'Volkswagen'),
    ('CAR-048', 'Hyundai Santa Fe', 'Hyundai'),
    ('CAR-049', 'Kia Sorento', 'Kia'),
    ('CAR-050', 'Nissan Pathfinder', 'Nissan'),
    ('CAR-051', 'Subaru Ascent', 'Subaru'),
    ('CAR-052', 'Mazda CX-9', 'Mazda'),
    ('CAR-053', 'Chevrolet Traverse', 'Chevrolet'),
    ('CAR-054', 'Ford Expedition', 'Ford'),
    ('CAR-055', 'Toyota 4Runner', 'Toyota'),
    ('CAR-056', 'Honda Passport', 'Honda'),
    ('CAR-057', 'BMW X7', 'BMW'),
    ('CAR-058', 'Audi Q8', 'Audi'),
    ('CAR-059', 'Mercedes-Benz GLS', 'Mercedes-Benz'),
    ('CAR-060', 'Volkswagen ID.4', 'Volkswagen'),
    ('CAR-061', 'Hyundai Ioniq 5', 'Hyundai'),
    ('CAR-062', 'Kia EV6', 'Kia'),
    ('CAR-063', 'Nissan Ariya', 'Nissan'),
    ('CAR-064', 'Subaru Solterra', 'Subaru'),
    ('CAR-065', 'Mazda MX-30', 'Mazda'),
    ('CAR-066', 'Chevrolet Bolt EV', 'Chevrolet'),
    ('CAR-067', 'Ford Mustang Mach-E', 'Ford'),
    ('CAR-068', 'Toyota bZ4X', 'Toyota'),
    ('CAR-069', 'Honda HR-V', 'Honda'),
    ('CAR-070', 'BMW i4', 'BMW'),
    ('CAR-071', 'Audi e-tron GT', 'Audi'),
    ('CAR-072', 'Mercedes-Benz EQB', 'Mercedes-Benz'),
    ('CAR-073', 'Volkswagen ID.3', 'Volkswagen'),
    ('CAR-074', 'Hyundai Kona Electric', 'Hyundai'),
    ('CAR-075', 'Kia Niro EV', 'Kia'),
    ('CAR-076', 'Nissan Leaf', 'Nissan'),
    ('CAR-077', 'Subaru Crosstrek', 'Subaru'),
    ('CAR-078', 'Mazda2', 'Mazda'),
    ('CAR-079', 'Chevrolet Trailblazer', 'Chevrolet'),
    ('CAR-080', 'Ford Bronco Sport', 'Ford'),
    ('CAR-081', 'Toyota Sequoia', 'Toyota'),
    ('CAR-082', 'Honda Ridgeline', 'Honda'),
    ('CAR-083', 'BMW Z4', 'BMW'),
    ('CAR-084', 'Audi TT', 'Audi'),
    ('CAR-085', 'Mercedes-Benz SL-Class', 'Mercedes-Benz'),
    ('CAR-086', 'Volkswagen Arteon', 'Volkswagen'),
    ('CAR-087', 'Hyundai Veloster', 'Hyundai'),
    ('CAR-088', 'Kia Stinger', 'Kia'),
    ('CAR-089', 'Nissan 370Z', 'Nissan'),
    ('CAR-090', 'Subaru BRZ', 'Subaru'),
    ('CAR-091', 'Mazda MX-5 Miata', 'Mazda'),
    ('CAR-092', 'Chevrolet Camaro', 'Chevrolet'),
    ('CAR-093', 'Ford Mustang', 'Ford'),
    ('CAR-094', 'Toyota Supra', 'Toyota'),
    ('CAR-095', 'Honda Civic Type R', 'Honda'),
    ('CAR-096', 'BMW M3', 'BMW'),
    ('CAR-097', 'Audi RS5', 'Audi'),
    ('CAR-098', 'Mercedes-Benz AMG GT', 'Mercedes-Benz'),
    ('CAR-099', 'Volkswagen Golf R', 'Volkswagen'),
    ('CAR-100', 'Hyundai Elantra N', 'Hyundai');

-- Inserção de 100 peças
INSERT INTO pecas (nome, descricao, serial_number, fabricante, id_carro)
VALUES
    ('Filtro de Óleo', 'Filtro de óleo para motores a gasolina.', 'PCA-001', 'Bosch', 1),
    ('Pastilha de Freio', 'Pastilhas de freio dianteiras.', 'PCA-002', 'Akebono', 2),
    ('Amortecedor Traseiro', 'Amortecedor traseiro para veículos de passeio.', 'PCA-003', 'KYB', 3),
    ('Velas de Ignição', 'Velas de ignição para motores de combustão.', 'PCA-004', 'NGK', 4),
    ('Bateria', 'Bateria de 12V para carros.', 'PCA-005', 'Exide', 5),
    ('Lâmpada de Farol', 'Lâmpada de farol H7.', 'PCA-006', 'Philips', 6),
    ('Disco de Freio', 'Disco de freio dianteiro.', 'PCA-007', 'Zimmermann', 7),
    ('Correia Dentada', 'Correia dentada para motores.', 'PCA-008', 'Dayco', 8),
    ('Kit de Embreagem', 'Kit de embreagem completo.', 'PCA-009', 'Valeo', 9),
    ('Radiador', 'Radiador de água para motor.', 'PCA-010', 'Mishimoto', 10),
    ('Filtro de Ar', 'Filtro de ar para motor.', 'PCA-011', 'K&N', 11),
    ('Bomba de Água', 'Bomba de água para motor.', 'PCA-012', 'Gates', 12),
    ('Limpador de Para-brisa', 'Limpador de para-brisa de 24 polegadas.', 'PCA-013', 'Trico', 13),
    ('Cabo de Velas', 'Cabo de velas de ignição.', 'PCA-014', 'Bosch', 14),
    ('Sensor de Oxigênio', 'Sensor de oxigênio para controle de emissão.', 'PCA-015', 'NTK', 15),
    ('Escapamento', 'Sistema de escapamento traseiro.', 'PCA-016', 'MagnaFlow', 16),
    ('Kit de Distribuição', 'Kit completo de distribuição.', 'PCA-017', 'INA', 17),
    ('Amortecedor Dianteiro', 'Amortecedor dianteiro para suspensão.', 'PCA-018', 'Monroe', 18),
    ('Correia de Acessórios', 'Correia de acessórios para motor.', 'PCA-019', 'Continental', 19),
    ('Tampa de Válvula', 'Tampa de válvula para motor.', 'PCA-020', 'Fel-Pro', 20),
    ('Filtro de Combustível', 'Filtro de combustível para motores a gasolina.', 'PCA-021', 'WIX', 21),
    ('Correia Dentada', 'Correia dentada para motor.', 'PCA-022', 'Dayco', 22),
    ('Pastilha de Freio Traseira', 'Pastilhas de freio traseiras.', 'PCA-023', 'Brembo', 23),
    ('Velas de Ignição Iridium', 'Velas de ignição tipo Iridium.', 'PCA-024', 'NGK', 24),
    ('Bateria AGM', 'Bateria AGM de 12V.', 'PCA-025', 'Optima', 25),
    ('Lâmpada de Farol LED', 'Lâmpada de farol LED H7.', 'PCA-026', 'Sylvania', 26),
    ('Disco de Freio Traseiro', 'Disco de freio traseiro.', 'PCA-027', 'EBC', 27),
    ('Kit de Embreagem Dual', 'Kit de embreagem com volante dual.', 'PCA-028', 'Sachs', 28),
    ('Radiador de Alumínio', 'Radiador de alumínio para motor.', 'PCA-029', 'BeCool', 29),
    ('Filtro de Ar Esportivo', 'Filtro de ar esportivo.', 'PCA-030', 'AEM', 30),
    ('Bomba de Água Alta Performance', 'Bomba de água de alta performance.', 'PCA-031', 'Gates', 31),
    ('Limpador de Para-brisa Premium', 'Limpador de para-brisa premium de 24 polegadas.', 'PCA-032', 'Bosch', 32),
    ('Cabo de Velas Ignition', 'Cabo de velas Ignition.', 'PCA-033', 'Denso', 33),
    ('Sensor de Estacionamento', 'Sensor de estacionamento dianteiro.', 'PCA-034', 'Hella', 34),
    ('Escapamento esportivo', 'Sistema de escapamento esportivo.', 'PCA-035', 'Borla', 35),
    ('Kit de Distribuição Premium', 'Kit premium de distribuição.', 'PCA-036', 'Continental', 36),
    ('Amortecedor Traseiro Esportivo', 'Amortecedor traseiro esportivo.', 'PCA-037', 'Koni', 37),
    ('Correia de Acessórios Reforçada', 'Correia de acessórios reforçada.', 'PCA-038', 'Gates', 38),
    ('Tampa de Válvula de Alumínio', 'Tampa de válvula de alumínio.', 'PCA-039', 'ARP', 39),
    ('Filtro de Combustível Esportivo', 'Filtro de combustível esportivo.', 'PCA-040', 'HMF', 40),
    ('Correia Dentada Alta Performance', 'Correia dentada de alta performance.', 'PCA-041', 'Dayco', 41),
    ('Pastilha de Freio Cerâmica', 'Pastilhas de freio cerâmicas.', 'PCA-042', 'EBC', 42),
    ('Velas de Ignição de Platinum', 'Velas de ignição tipo Platinum.', 'PCA-043', 'Bosch', 43),
    ('Bateria Lithium', 'Bateria Lithium de 12V.', 'PCA-044', 'Braille', 44),
    ('Lâmpada de Farol Xenon', 'Lâmpada de farol Xenon H7.', 'PCA-045', 'Osram', 45),
    ('Disco de Freio de Alta Performance', 'Disco de freio de alta performance.', 'PCA-046', 'PowerStop', 46),
    ('Kit de Embreagem Sport', 'Kit de embreagem sport.', 'PCA-047', 'Clutch Masters', 47),
    ('Radiador de Alto Fluxo', 'Radiador de alto fluxo.', 'PCA-048', 'C&R Racing', 48),
    ('Filtro de Ar de Alto Fluxo', 'Filtro de ar de alto fluxo.', 'PCA-049', 'Injen', 49),
    ('Bomba de Água Racing', 'Bomba de água racing.', 'PCA-050', 'Mishimoto', 50),
    ('Limpador de Para-brisa Ultrassônico', 'Limpador de para-brisa ultrassônico.', 'PCA-051', 'Rain-X', 51),
    ('Cabo de Velas de Silicone', 'Cabo de velas de silicone.', 'PCA-052', 'Accell', 52),
    ('Sensor de O2 Racing', 'Sensor de O2 racing.', 'PCA-053', 'Bosch', 53),
    ('Escapamento de Inox', 'Sistema de escapamento de inox.', 'PCA-054', 'Stainless', 54),
    ('Kit de Distribuição Racing', 'Kit de distribuição racing.', 'PCA-055', 'Melling', 55),
    ('Amortecedor de Alto Desempenho', 'Amortecedor de alto desempenho.', 'PCA-056', 'Bilstein', 56),
    ('Correia de Acessórios Sport', 'Correia de acessórios sport.', 'PCA-057', 'Continental', 57),
    ('Tampa de Válvula de Carbono', 'Tampa de válvula de carbono.', 'PCA-058', 'Inconel', 58),
    ('Filtro de Combustível Racing', 'Filtro de combustível racing.', 'PCA-059', 'FRAM', 59),
    ('Correia Dentada Racing', 'Correia dentada racing.', 'PCA-060', 'Gates', 60),
    ('Pastilha de Freio de Alto Desempenho', 'Pastilhas de freio de alto desempenho.', 'PCA-061', 'Hawk', 61),
    ('Velas de Ignição de Iridium Racing', 'Velas de ignição de iridium racing.', 'PCA-062', 'NGK', 62),
    ('Bateria de Alto Desempenho', 'Bateria de alto desempenho.', 'PCA-063', 'Odyssey', 63),
    ('Lâmpada de Farol de LED Racing', 'Lâmpada de farol LED racing.', 'PCA-064', 'Hikari', 64),
    ('Disco de Freio Carbono', 'Disco de freio de carbono.', 'PCA-065', 'AP Racing', 65),
    ('Kit de Embreagem Racing', 'Kit de embreagem racing.', 'PCA-066', 'Exedy', 66),
    ('Radiador Racing', 'Radiador racing.', 'PCA-067', 'Koyo', 67),
    ('Filtro de Ar Racing', 'Filtro de ar racing.', 'PCA-068', 'Sprint', 68),
    ('Bomba de Água de Alta Performance', 'Bomba de água de alta performance.', 'PCA-069', 'Water Pump', 69),
    ('Limpador de Para-brisa Racing', 'Limpador de para-brisa racing.', 'PCA-070', 'Bosch', 70),
    ('Cabo de Velas Racing', 'Cabo de velas racing.', 'PCA-071', 'Performance', 71),
    ('Sensor de Estacionamento Premium', 'Sensor de estacionamento premium.', 'PCA-072', 'Parktronics', 72),
    ('Escapamento Racing', 'Sistema de escapamento racing.', 'PCA-073', 'Akrapovic', 73),
    ('Kit de Distribuição Performance', 'Kit de distribuição performance.', 'PCA-074', 'GT Performance', 74),
    ('Amortecedor Racing', 'Amortecedor racing.', 'PCA-075', 'Koni', 75),
    ('Correia de Acessórios Premium', 'Correia de acessórios premium.', 'PCA-076', 'Dayco', 76),
    ('Tampa de Válvula Racing', 'Tampa de válvula racing.', 'PCA-077', 'Alpina', 77),
    ('Filtro de Combustível Premium', 'Filtro de combustível premium.', 'PCA-078', 'RAC', 78),
    ('Correia Dentada Premium', 'Correia dentada premium.', 'PCA-079', 'Gates', 79),
    ('Pastilha de Freio Premium', 'Pastilhas de freio premium.', 'PCA-080', 'Brembo', 80),
    ('Velas de Ignição Premium', 'Velas de ignição premium.', 'PCA-081', 'Bosch', 81),
    ('Bateria Premium', 'Bateria premium.', 'PCA-082', 'Varta', 82),
    ('Lâmpada de Farol Premium', 'Lâmpada de farol premium.', 'PCA-083', 'Osram', 83),
    ('Disco de Freio Premium', 'Disco de freio premium.', 'PCA-084', 'EBC', 84),
    ('Kit de Embreagem Premium', 'Kit de embreagem premium.', 'PCA-085', 'Valeo', 85),
    ('Radiador Premium', 'Radiador premium.', 'PCA-086', 'Nissens', 86),
    ('Filtro de Ar Premium', 'Filtro de ar premium.', 'PCA-087', 'K&N', 87),
    ('Bomba de Água Premium', 'Bomba de água premium.', 'PCA-088', 'Gates', 88),
    ('Limpador de Para-brisa Premium', 'Limpador de para-brisa premium.', 'PCA-089', 'Rain-X', 89),
    ('Cabo de Velas Premium', 'Cabo de velas premium.', 'PCA-090', 'NGK', 90),
    ('Sensor de O2 Premium', 'Sensor de O2 premium.', 'PCA-091', 'Denso', 91),
    ('Escapamento Premium', 'Sistema de escapamento premium.', 'PCA-092', 'Remus', 92),
    ('Kit de Distribuição Premium', 'Kit de distribuição premium.', 'PCA-093', 'Melling', 93),
    ('Amortecedor Premium', 'Amortecedor premium.', 'PCA-094', 'Bilstein', 94),
    ('Correia de Acessórios Premium', 'Correia de acessórios premium.', 'PCA-095', 'Continental', 95),
    ('Tampa de Válvula Premium', 'Tampa de válvula premium.', 'PCA-096', 'Fel-Pro', 96),
    ('Filtro de Combustível Premium', 'Filtro de combustível premium.', 'PCA-097', 'Bosch', 97),
    ('Correia Dentada Premium', 'Correia dentada premium.', 'PCA-098', 'Dayco', 98),
    ('Pastilha de Freio Premium', 'Pastilhas de freio premium.', 'PCA-099', 'EBC', 99),
    ('Velas de Ignição Premium', 'Velas de ignição premium.', 'PCA-100', 'NGK', 100);
